language: python
python:
  - "3.8"
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  distributions: sdist bdist_wheel
  skip_existing: true
  provider: pypi
  server: https://test.pypi.org/legacy/
  username: "__token__"
  password: "pypi-AgENdGVzdC5weXBpLm9yZwIkNDhjYzRkMWMtMDk0Ny00Y2YyLWE3NjAtNTBhMWJmMTcyOTgxAAJFeyJwZXJtaXNzaW9ucyI6IHsicHJvamVjdHMiOiBbImRhbmllbC1zaW1wbGVyZXF1ZXN0Il19LCAidmVyc2lvbiI6IDF9AAAGIBjIxvmjrzoY1IkWI6Q9gRVHO3iad35OpUaaPRIUhZet"